name: MiniJuvix CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ["9.2.3"]
    steps:
      - uses: actions/cache@v3
        name: Cache Stack
        id: cache
        env:
          cache-name: cache-env
        with:
          path: |
            ~/.stack
            minijuvix/.stack-work
            minijuvix/.hie
          key: ${{ runner.os }}-v1-build-${{ matrix.ghc }}-${{ hashFiles('minijuvix/src/**/*.hs', 'minijuvix/app/**/*.hs',  'minijuvix/test/**/*.hs', 'minijuvix/package.yaml', 'minijuvix/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-v1-build-${{ matrix.ghc }}-
            ${{ runner.os }}-v1-build-
            ${{ runner.os }}-v1-

      - uses: haskell/actions/setup@v1
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - name: Checkout MiniJuvix
        uses: actions/checkout@v3
        with:
          repository: heliaxdev/minijuvix
          path: minijuvix
      
      - name: Install MiniJuvix
        run: |
          cd minijuvix
          echo "$GITHUB_WORKSPACE/.local/bin" >> $GITHUB_PATH
          make install

      - name: Checkout Std Library
        uses: actions/checkout@v3
 
      - name: HTML
        run: |
          minijuvix html index.mjuvix --theme ayu --recursive --print-metadata --output-dir=docs/

      - if: github.event.pull_request.merged == true
        name: Deploy HTML to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          enable_jekyll: false
