name: Juvix standard library CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    - cron: '0 3 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Juvix
        uses: actions/checkout@v3
        with:
          repository: anoma/juvix
          path: juvix
          submodules: true

      - name: install LLVM
        run: |
          sudo apt install llvm

      - name: Make runtime
        run: |
          cd juvix
          make runtime

      - name: Stack setup
        id: stack
        uses: freckle/stack-action@v4
        with:
          working-directory: juvix
          test: false
          fast: false
      
      - name: Install Juvix
        run: |
          cd juvix
          echo "$GITHUB_WORKSPACE/.local/bin" >> $GITHUB_PATH
          stack install

      - name: Checkout Std Library
        uses: actions/checkout@v3
 
      - name : Typecheck library code
        run : make check

      - name: HTML
        run: make html

      - name: test
        run: make test

      - name: check-format-and-typecheck-all
        shell: bash
        run: |
          make check-format && make typecheck

      - name: Deploy HTML to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: >-
          github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          enable_jekyll: false
